[global]
timeout_ms=500
retry_count=3
retry_sleep_ms=10000
comm_loss=保持
verbose=2
hex_dump=1

[Channel_1]
ip=127.0.0.1
port=502
scan_ms=1000
keep_alive_addr=-1

[Template_保护装置]
di_001 = addr=0, func=01, qty=32, point=2, invert=0, comm_loss=保持
;ai_001 = addr=0, func=03, point=1, dtype=uint16, endian=AB, scale=1.0, offset=0, comm_loss=保持
; FC05 遥控写回 + 500ms 脉冲（写入后 500ms 自动写相反值 OFF）
do_001 = addr=0, func=05, point=1, invert=0, pulse_ms=5000
; FC05 遥控写回，无脉冲（仅写入，不复位）
do_002 = addr=1, func=05, point=2, invert=0
[Device_1]
channel=1
station_id=1
template=保护装置
desc=测试设备
